version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app 
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    command: npm run dev -- --host 0.0.0.0 
    
  neo4j:
    image: neo4j:5.26.0-community
    container_name: neo4j_db
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password

volumes:
  neo4j_data: