version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app 
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true


  mongo:
    image: mongo:4.4
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - novel-ai-data:/data/db/
    ports:
      - '27017:27017'

volumes:
  novel-ai-data: