version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app 
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true

  neo4j:
    image: neo4j:5.26.0-community
    container_name: neo4j_db
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password

volumes:
  neo4j_data: